import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                "surface-dim": "#d9d9e4",
                "surface-container-highest": "#e1e2ec",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#2e3038",
                "on-surface-variant": "#434654",
                "on-tertiary-container": "#6de2ff",
                "on-primary-fixed-variant": "#004b72",
                "error-container": "#ffdad6",
                "on-secondary": "#ffffff",
                "surface": "#faf8ff",
                "surface-container": "#ededf8",
                "on-primary-container": "#acd8ff",
                "surface-bright": "#faf8ff",
                "on-background": "#191b23",
                "secondary": "#4648d4",
                "surface-variant": "#e1e2ec",
                "secondary-fixed-dim": "#c0c1ff",
                "on-primary-fixed": "#001e31",
                "primary": "#00476d",
                "on-secondary-fixed-variant": "#2f2ebe",
                "on-error": "#ffffff",
                "primary-fixed": "#cce5ff",
                "surface-container-low": "#f3f3fd",
                "inverse-primary": "#90cdff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#e1e0ff",
                "tertiary-fixed-dim": "#4cd7f6",
                "error": "#ba1a1a",
                "on-surface": "#191b23",
                "primary-container": "#006090",
                "outline-variant": "#c3c6d6",
                "surface-container-high": "#e7e7f2",
                "on-primary": "#ffffff",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#07006c",
                "tertiary-container": "#006475",
                "primary-fixed-dim": "#90cdff",
                "outline": "#737685",
                "tertiary-fixed": "#acedff",
                "surface-tint": "#006496",
                "on-secondary-container": "#fffbff",
                "tertiary": "#004a58",
                "on-tertiary-fixed": "#001f26",
                "on-tertiary-fixed-variant": "#004e5c",
                "background": "#faf8ff",
                "inverse-on-surface": "#f0f0fb",
                "secondary-container": "#6063ee",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            fontFamily: {
                sans: ["Manrope", ...defaultTheme.fontFamily.sans],
                headline: ["Be Vietnam Pro", ...defaultTheme.fontFamily.sans],
                body: ["Manrope", ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
